### ISSUE TITLE
Room setup

### ISSUE THREAD

**Issue by fabricekalvanda** [MobileApps-Cascadia/pollinator-pathway-android#62]

**Comment by Bansenauer-Cascadia** [comment]
@fabricekalvanda Don't close the issue until you have merged the branch or combined it with another issue.

I recommend you complete the pull request as soon as possible. You may have to ask people individually to review your [pull request #63](https://github.com/MobileApps-Cascadia/pollinator-pathway-android/pull/63) .Get this merged so that others can start working with you code
